### ISSUE TITLE
Image grid has too many rows

### ISSUE THREAD

**Issue by eldelacajita** [EcosistemaUrbano/local_in#51]
The thumbnail grid should be limited to 4 rows and, ideally, vertically centered with the next/back arrows.

![thumbnail_grid_error](https://cloud.githubusercontent.com/assets/2880679/5757023/191b3df4-9cb7-11e4-8c06-07da0e7f1d5c.png)

**Comment by skotperez** [comment]
Done: https://github.com/EcosistemaUrbano/local_in/commit/67bc0461f9e5422eff80cc5f8b2ec492e11a4230

**Comment by eldelacajita** [comment]
Works great now, thanks.
