### ISSUE TITLE
Tag chooser shows only some of them

### ISSUE THREAD

**Issue by eldelacajita** [EcosistemaUrbano/local_in#52]
As the number of existing tags increases, only the first ones show up on the entry form. The rest don't fit. We should either make the tags smaller as the number increases, or allow that area to be scrollable.

![hidden_tags](https://cloud.githubusercontent.com/assets/2880679/5757056/8a545226-9cb7-11e4-8895-92d077f2972a.png)

**Comment by skotperez** [comment]
I have increased the amount of visible tags and change the criteria to show them: now the form shows the top 50 most used tags https://github.com/EcosistemaUrbano/local_in/commit/ccc11c0901c5994513abf94b34786b70cf575c4d

**Comment by eldelacajita** [comment]
That should work!
