### ISSUE TITLE
Make location link and related link more visible

### ISSUE THREAD

**Issue by eldelacajita** [EcosistemaUrbano/local_in#53]
Like in the first message in this mockup. 

![links](https://cloud.githubusercontent.com/assets/2880679/5757367/a95e7edc-9cba-11e4-81d3-9fd4868d4bcf.png)

**Comment by skotperez** [comment]
Done: https://github.com/EcosistemaUrbano/local_in/commit/8b1b6a28dcb005a3905c8de6db6d022161f79b69

**Comment by eldelacajita** [comment]
Great, thanks!

**Comment by eldelacajita** [comment]
Sorry, Alfonso. There was a misunderstanding here. You have highlighted the "permalink" link. That one should remain as it was. The one we want to make more visible is the "related link" you can include when creating a post (link to a video, a website, etc.). This feature is now lost.
