### ISSUE TITLE
Typo error on es_ES.po

### ISSUE THREAD

**Issue by xomnot** [EcosistemaUrbano/local_in#72]
There is a tiny typo error on , [https://github.com/EcosistemaUrbano/local_in/blob/master/localin/languages/es_ES.po](url) which doesn't traslates the phrase:

`msgid "This is the message you have published. Thanks for participage, %s."
msgstr "Este es el mensaje que has publicado. Gracias por participar, %s."`

It is on "thanks for **participage**", should be participate ;)

Greetings!

**Comment by eldelacajita** [comment]
Well spotted! Actually, it should be "participating", in the context of that sentence.
